spring:
  datasource:
    username: javaweb
    password: 123456
    url: jdbc:mysql://121.40.110.36:3306/db?useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.javaweb.shopping.entity
server:
  port: 8081
